// client/src/components/layout/SiteHeader.vue
<script setup lang="ts">
import { navItems } from '../../lib/links'
import ThemeToggle from './ThemeToggle.vue'
</script>

<template>
  <header class="header">
    <div class="headerInner">
      <a class="brand" href="#">
        <span class="brandText">stylesense</span>
      </a>

      <nav class="nav" aria-label="Primary">
        <a v-for="item in navItems" :key="item.label" class="navItem" :href="item.href">
          <span>{{ item.label }}</span>
          <svg v-if="item.hasMenu" class="chev" viewBox="0 0 20 20" fill="none" aria-hidden="true">
            <path d="M5 7.5L10 12.5L15 7.5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
          </svg>
        </a>
      </nav>

      <div class="actions">
        <ThemeToggle />
        <a class="download" href="#">
          <span>Download</span>
          <svg class="arrow" viewBox="0 0 20 20" fill="none" aria-hidden="true">
            <path d="M8 5l5 5-5 5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
          </svg>
        </a>
      </div>
    </div>
  </header>
</template>

<style scoped>
.header {
  position: sticky;
  top: 0;
  z-index: 10;
  background: color-mix(in srgb, var(--bg) 92%, transparent);
  backdrop-filter: blur(10px);
}

.headerInner {
  max-width: 1120px;
  margin: 0 auto;
  padding: 20px 24px;
  display: grid;
  grid-template-columns: 1fr auto 1fr;
  align-items: center;
  gap: 12px;
}

.brand {
  display: inline-flex;
  align-items: center;
  text-decoration: none;
  color: inherit;
}

.brandText {
  font-family: var(--ui-font);
  font-weight: 600;
  letter-spacing: -0.02em;
}

.nav {
  justify-self: center;
  display: flex;
  align-items: center;
  gap: 28px;
  font-family: var(--ui-font);
  font-weight: 500;
  color: var(--text);
}

.navItem {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  text-decoration: none;
  color: inherit;
  opacity: 0.92;
}

.navItem:hover {
  opacity: 1;
}

.chev {
  width: 16px;
  height: 16px;
  opacity: 0.7;
}

.actions {
  justify-self: end;
  display: inline-flex;
  align-items: center;
  gap: 14px;
}

.download {
  display: inline-flex;
  align-items: center;
  gap: 12px;
  padding: 16px 22px;
  border-radius: 16px;
  background: var(--cta-primary-bg);
  color: var(--cta-primary-fg);
  text-decoration: none;
  font-family: var(--ui-font);
  font-weight: 600;
  box-shadow: var(--shadow-strong);
}

.download:hover {
  filter: brightness(1.04);
}

.arrow {
  width: 18px;
  height: 18px;
}

@media (max-width: 820px) {
  .headerInner {
    grid-template-columns: 1fr 1fr;
  }

  .nav {
    display: none;
  }
}
</style>

// src/components/layout/SiteHeader.tsx
import { Link } from '@tanstack/react-router'
import { SignedIn, SignedOut } from '@clerk/clerk-react'
import { navItems } from '../../lib/links'
import HeaderUser from '../../integrations/clerk/header-user'
import ThemeToggle from './ThemeToggle'

export default function SiteHeader() {
  return (
    <header className="sticky top-0 z-10 bg-[color-mix(in_srgb,var(--bg)_92%,transparent)] backdrop-blur-[10px]">
      <div className="mx-auto grid max-w-[1120px] grid-cols-[1fr_auto_1fr] items-center gap-3 px-6 py-5 max-[820px]:grid-cols-[1fr_1fr]">
        <Link className="inline-flex items-center no-underline text-[color:var(--text)]" to="/">
          <span className="font-[family-name:var(--ui-font)] font-semibold tracking-[-0.02em]">stylesense</span>
        </Link>

        <nav
          className="justify-self-center flex items-center gap-7 font-[family-name:var(--ui-font)] font-medium text-[color:var(--text)] max-[820px]:hidden"
          aria-label="Primary"
        >
          {navItems.map((item) => (
            <a
              key={item.label}
              className="inline-flex items-center gap-2 no-underline text-inherit opacity-90 hover:opacity-100"
              href={item.href}
            >
              <span>{item.label}</span>
              {item.hasMenu ? (
                <svg className="h-4 w-4 opacity-70" viewBox="0 0 20 20" fill="none" aria-hidden="true">
                  <path
                    d="M5 7.5L10 12.5L15 7.5"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  />
                </svg>
              ) : null}
            </a>
          ))}
        </nav>

        <div className="justify-self-end inline-flex items-center gap-3.5">
          <ThemeToggle />
          <HeaderUser />
          <SignedOut>
            <Link
              className="inline-flex items-center gap-3 rounded-2xl bg-[color:var(--cta-primary-bg)] px-[22px] py-4 font-[family-name:var(--ui-font)] font-semibold text-[color:var(--cta-primary-fg)] no-underline shadow-[var(--shadow-strong)] hover:brightness-[1.04]"
              to="/sign-up"
            >
              <span>Sign up</span>
              <svg className="h-[18px] w-[18px]" viewBox="0 0 20 20" fill="none" aria-hidden="true">
                <path
                  d="M8 5l5 5-5 5"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            </Link>
          </SignedOut>
          <SignedIn>
            <Link
              className="inline-flex items-center gap-3 rounded-2xl bg-[color:var(--cta-primary-bg)] px-[22px] py-4 font-[family-name:var(--ui-font)] font-semibold text-[color:var(--cta-primary-fg)] no-underline shadow-[var(--shadow-strong)] hover:brightness-[1.04]"
              to="/dashboard"
            >
              <span>Dashboard</span>
              <svg className="h-[18px] w-[18px]" viewBox="0 0 20 20" fill="none" aria-hidden="true">
                <path
                  d="M8 5l5 5-5 5"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            </Link>
          </SignedIn>
        </div>
      </div>
    </header>
  )
}
